"""Built-in Zero Factory Cron Jobs facade module.

Maintained for backward compatibility. All implementations have been modularized
into the `cron` package.
"""

from cron import (
    BUILTIN_CRON_JOBS,
    CORE_CRON_JOBS,
    CRON_RUN_OUTPUT_TAIL_CHARS,
    CRON_RUN_TIMEOUT,
    DAILY_REPORT_PROMPT,
    DEFAULT_DB_PATH,
    TASK_QUEUE_CHECK_PROMPT,
    _active_cron_runs,
    _apply_job_field_updates,
    _c,
    _load_env_defaults,
    build_board_scanner_prompt,
    cleanup_duplicate_root_jobs,
    compute_job_next_run,
    ensure_builtin_cron_jobs,
    get_all_builtin_cron_jobs,
    get_scanner_cron_config,
    get_db_path,
    get_target_jobs_files,
    is_cron_scheduler_enabled,
    list_builtin_jobs,
    load_jobs_from_file,
    prune_board_cron_job,
    reap_active_cron_runs,
    reset_builtin_job,
    resolve_board_repo_path,
    save_jobs_to_file,
    set_cron_scheduler_enabled,
    tick_builtin_cron,
    toggle_builtin_job,
    trigger_builtin_job,
    update_builtin_job,
)

__all__ = [
    "BUILTIN_CRON_JOBS",
    "CORE_CRON_JOBS",
    "CRON_RUN_OUTPUT_TAIL_CHARS",
    "CRON_RUN_TIMEOUT",
    "DAILY_REPORT_PROMPT",
    "DEFAULT_DB_PATH",
    "TASK_QUEUE_CHECK_PROMPT",
    "_active_cron_runs",
    "_apply_job_field_updates",
    "_c",
    "_load_env_defaults",
    "build_board_scanner_prompt",
    "cleanup_duplicate_root_jobs",
    "compute_job_next_run",
    "ensure_builtin_cron_jobs",
    "get_all_builtin_cron_jobs",
    "get_scanner_cron_config",
    "get_db_path",
    "get_target_jobs_files",
    "is_cron_scheduler_enabled",
    "list_builtin_jobs",
    "load_jobs_from_file",
    "prune_board_cron_job",
    "reap_active_cron_runs",
    "reset_builtin_job",
    "resolve_board_repo_path",
    "save_jobs_to_file",
    "set_cron_scheduler_enabled",
    "tick_builtin_cron",
    "toggle_builtin_job",
    "trigger_builtin_job",
    "update_builtin_job",
]
