"""Unit tests for dashboard/openwiki_service.py."""

import subprocess
from pathlib import Path

import cron.definitions as defs

from dashboard.openwiki_service import (
    OPENWIKI_RELATIVE_DIR,
    build_openwiki_setup_task_prompt,
    check_board_openwiki_status,
    create_openwiki_setup_task,
)
from dashboard.plugin_api import BoardCreate, create_board


def test_build_openwiki_setup_task_prompt():
    prompt = build_openwiki_setup_task_prompt("test-board")
    assert OPENWIKI_RELATIVE_DIR in prompt
    assert "openwiki" in prompt
    assert "AGENTS.md" in prompt
    assert "test-board" in prompt
    assert "npm install -g openwiki" in prompt
    # The wiki must be generated by the openwiki CLI, never manually, using the
    # `code` subcommand (not the bare top-level flags).
    assert "openwiki code --init" in prompt
    assert "openwiki --init" not in prompt  # bare top-level form must not be used
    # Future refreshes/updates use the `code` subcommand; the --print variant
    # is no longer offered (only `openwiki code --update`).
    assert "openwiki code --update" in prompt
    assert "openwiki code --update --print" not in prompt
    assert "--print" not in prompt
    assert "never manually" in prompt
    assert "manually create" in prompt
    # No fallback to hand-authoring the wiki is offered.
    assert "manually structure" not in prompt
    assert "if non-interactive" not in prompt
    # On CLI failure the worker must block, not improvise.
    assert "BLOCK the task" in prompt
    # Detection/verification keys off the CLI's machine-readable JSON ledger,
    # not the Markdown index.md the CLI also writes.
    assert ".page-manifest.json" in prompt
    assert "machine-readable JSON" in prompt
    # The prompt grounds verification in the CLI's standard artifacts: the
    # machine-readable JSON page ledger plus the canonical quickstart.md
    # entry point, and explicitly bars keying off the Markdown index.md.
    assert "openwiki/quickstart.md" in prompt
    assert "standard" in prompt
    assert "Do NOT key off" in prompt
    assert "index.md" in prompt  # only inside the "Do NOT key off" prohibition


def test_openwiki_status_missing_board(initialized_db: Path):
    res = check_board_openwiki_status("nonexistent-board")
    assert res["ok"] is False
    assert res["has_openwiki"] is False


def test_openwiki_status_and_task_lifecycle(initialized_db: Path, tmp_path: Path):
    # Create a dummy repo with git
    repo_dir = tmp_path / "dummy_repo"
    repo_dir.mkdir(parents=True)
    (repo_dir / ".git").mkdir()

    # Create board pointing to this local directory
    b_res = create_board(
        BoardCreate(
            git_url=str(repo_dir),
            description="Local dummy repo",
            auto_setup_precommit=False,
        )
    )
    slug = b_res["slug"]

    # Initial check: no openwiki directory
    status = check_board_openwiki_status(slug)
    assert status["ok"] is True
    assert status["has_openwiki"] is False
    assert status["pending_task_id"] is None

    # Trigger openwiki setup task
    setup_res = create_openwiki_setup_task(slug)
    assert setup_res["ok"] is True
    assert setup_res["already_exists"] is False
    task_id = setup_res["task_id"]
    assert task_id is not None

    # Check status again: pending task should now be detected
    status2 = check_board_openwiki_status(slug)
    assert status2["has_openwiki"] is False
    assert status2["pending_task_id"] == task_id
    assert status2["pending_task_status"] == "todo"

    # Calling create_openwiki_setup_task again should deduplicate
    setup_res2 = create_openwiki_setup_task(slug)
    assert setup_res2["ok"] is True
    assert setup_res2["already_exists"] is True
    assert setup_res2["task_id"] == task_id

    # Create openwiki/ directory with the CLI's machine-readable JSON ledger
    ow_dir = repo_dir / "openwiki"
    ow_dir.mkdir(parents=True, exist_ok=True)
    manifest_file = ow_dir / ".page-manifest.json"
    manifest_file.write_text('{"schemaVersion": 1, "pages": {}}', encoding="utf-8")

    # Status check should now detect has_openwiki = True
    status3 = check_board_openwiki_status(slug)
    assert status3["has_openwiki"] is True
    assert status3["openwiki_path"] == str(ow_dir)
    # Preview is sourced from the JSON ledger, not the Markdown index.md
    assert "schemaVersion" in status3["wiki_index_preview"]


def test_openwiki_status_check_does_not_auto_clone(initialized_db: Path, monkeypatch):
    """Read-only openwiki status check must never spawn a git clone subprocess."""
    import shutil

    calls: list[list[str]] = []

    def fake_run(cmd, *args, **kwargs):
        calls.append(list(cmd))
        return subprocess.CompletedProcess(
            args=cmd, returncode=1, stdout=b"", stderr=b""
        )

    # Clean up any stale directory a previous (unfixed) run may have created,
    # so the end-of-test home-dir assertion stays hermetic.
    stale = Path.home() / "git" / "no-clone-org"
    if stale.exists():
        shutil.rmtree(stale, ignore_errors=True)

    # Create the board while conftest's ZEROFACTORY_SKIP_GIT is still set so
    # board creation itself does not enter the auto-clone branch.
    b_res = create_board(
        BoardCreate(
            git_url="https://github.com/no-clone-org/no-clone-repo-ow.git",
            description="Remote board without a local clone",
            auto_setup_precommit=False,
        )
    )
    slug = b_res["slug"]

    # Exercise the read-only status check with auto-clone fully enabled.
    monkeypatch.delenv("ZEROFACTORY_SKIP_GIT", raising=False)
    monkeypatch.delenv("ZEROFACTORY_AUTO_CLONE", raising=False)
    monkeypatch.setattr(defs.subprocess, "run", fake_run)

    res = check_board_openwiki_status(slug)

    assert res["ok"] is True
    assert res["has_openwiki"] is False
    clones = [c for c in calls if len(c) >= 2 and c[1] == "clone"]
    assert not clones, f"status check triggered git clone: {clones}"
    assert not (Path.home() / "git" / "no-clone-org").exists()
