"""Zero Factory OpenWiki Service — Status detection, prompt generation, and setup task management."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

_PLUGIN_ROOT = str(Path(__file__).resolve().parent.parent)
if _PLUGIN_ROOT not in sys.path:
    sys.path.insert(0, _PLUGIN_ROOT)
_DASHBOARD_ROOT = str(Path(__file__).resolve().parent)
if _DASHBOARD_ROOT not in sys.path:
    sys.path.insert(0, _DASHBOARD_ROOT)

try:
    from .setup_common import (
        check_board_setup_status,
        create_setup_task,
        get_repo_resolver,  # noqa: F401  (re-exported for API compatibility)
    )
except (ImportError, ValueError):
    from setup_common import (  # type: ignore
        check_board_setup_status,
        create_setup_task,
        get_repo_resolver,  # noqa: F401  (re-exported for API compatibility)
    )

OPENWIKI_RELATIVE_DIR = "openwiki"
# The openwiki CLI's canonical machine-readable artifact (its PAGE_MANIFEST_PATH
# constant). Detection and preview key off this JSON ledger, not the Markdown
# index.md the CLI also writes, so status reflects what the CLI actually produced.
OPENWIKI_PAGE_MANIFEST_RELPATH = f"{OPENWIKI_RELATIVE_DIR}/.page-manifest.json"
SETUP_OPENWIKI_TASK_TITLE = (
    "chore(repo): setup OpenWiki machine-readable agent documentation"
)
SETUP_OPENWIKI_TASK_DEDUP_KEY = "setup:openwiki"
SETUP_OPENWIKI_TASK_TITLE_PREFIX = "chore(repo): setup OpenWiki"


def build_openwiki_setup_task_prompt(
    board_slug: str, repo_path: Path | None = None
) -> str:
    """Generate structured instructions for zf-builder to generate OpenWiki agent docs via the openwiki CLI."""
    path_hint = f" (`{repo_path}`)" if repo_path else ""
    return f"""Set up OpenWiki machine-readable agent documentation for this repository{path_hint} on board `{board_slug}`.

## Target
Directory: `{OPENWIKI_RELATIVE_DIR}/` (generated by the `openwiki` CLI)
Pointers: `AGENTS.md` / `CLAUDE.md` (maintained by the `openwiki` CLI)

## Goal
Generate a high-signal, machine-readable architectural knowledge base in `{OPENWIKI_RELATIVE_DIR}/` (Docs for Agents pattern) using the **official `openwiki` CLI** and its standard artifacts, so agents consume the wiki instead of re-reading source. This optimizes context windows, slashes exploratory token consumption by 30–40%, and prevents multi-agent hallucination across Zero Factory workers (`zf-builder`, `zf-reviewer`, `zf-orchestrator`).

## Instructions
1. **Ensure the `openwiki` CLI is installed**:
   - Check: `openwiki --version` (requires Node.js >= 22.22.0).
   - If not installed, install it globally via npm:
     ```bash
     npm install -g openwiki
     ```
   - If a global install is impossible in this environment, run the same CLI on-demand: `npx -y openwiki --version`.

2. **Generate the wiki with the `openwiki` CLI — never manually**:
   - **CRITICAL: the wiki MUST be generated by the `openwiki` CLI. Do NOT hand-write, hand-structure, or manually create `{OPENWIKI_RELATIVE_DIR}/`, `AGENTS.md`, or `CLAUDE.md`.** If the CLI cannot complete a run in this environment, BLOCK the task (`hermes zerofactory block <task_id> --reason "<CLI error>"`) with the captured error output instead of falling back to manual wiki authoring.
   - Run from the repository root (always use the `code` subcommand, not the bare top-level flags):
     ```bash
     openwiki code --init
     ```
     Answer the onboarding prompts (provider, credentials, model) so the run completes; the CLI writes the generated wiki to `{OPENWIKI_RELATIVE_DIR}/`.
   - For future wiki refreshes/updates (after initial setup), use the matching `code` subcommand:
     ```bash
     openwiki code --update
     ```
   - **Verify the CLI's standard artifacts on disk** before proceeding — all are written by the CLI itself (never create or edit any of them by hand):
     - `{OPENWIKI_PAGE_MANIFEST_RELPATH}` — the CLI's machine-readable JSON page ledger (its `PAGE_MANIFEST_PATH` constant). Confirm it exists and parses as valid JSON with shape `{{"schemaVersion": 1, "pages": {{...}}}}`.
     - `{OPENWIKI_RELATIVE_DIR}/quickstart.md` — the CLI's standard canonical entry point, which a run must create and must never delete.
     - Do NOT key off `{OPENWIKI_RELATIVE_DIR}/index.md` or hand-write any Markdown page in `{OPENWIKI_RELATIVE_DIR}/` — the machine-readable JSON ledger is the source of truth.

3. **Confirm agent pointers (CLI-managed)**:
   - The `openwiki` CLI maintains the `AGENTS.md` and `CLAUDE.md` managed block (`<!-- OPENWIKI:START --> ... <!-- OPENWIKI:END -->`) at the repository root itself — do NOT edit that block by hand.
   - If the CLI left `AGENTS.md` without any reference to `{OPENWIKI_RELATIVE_DIR}/`, add an explicit reference section OUTSIDE the managed block, pointing at the CLI's standard entry point:
     ```markdown
     ## Repository Architecture & Agent Wiki
     For architectural overviews, subsystem maps, and module contracts, consult the machine-readable wiki in `{OPENWIKI_RELATIVE_DIR}/quickstart.md` before reading individual source files.
     ```

4. **Verify Precommit Checks**:
   - Run `./.zerofactory/precommit.sh` (or `git status`) in the repository to verify that format, build, and test checks execute cleanly.
   - Re-confirm the CLI's standard artifacts are present and well-formed: the machine-readable JSON ledger at `{OPENWIKI_PAGE_MANIFEST_RELPATH}` (the dashboard reads this JSON artifact) and the canonical `{OPENWIKI_RELATIVE_DIR}/quickstart.md` entry point.

5. **Complete Task**:
   - Mark task done via `hermes zerofactory move <task_id> done`.
   - (NOTE: Do NOT run git add/commit/push manually. The dispatcher automatically verifies precommit and stages/commits/opens PR upon task completion).
"""


def check_board_openwiki_status(board_slug: str) -> dict[str, Any]:
    """Check if openwiki/ exists for a board and check active setup task status."""
    return check_board_setup_status(
        board_slug,
        has_key="has_openwiki",
        path_key="openwiki_path",
        preview_key="wiki_index_preview",
        target_relpath=OPENWIKI_RELATIVE_DIR,
        title_prefix=SETUP_OPENWIKI_TASK_TITLE_PREFIX,
        dedup_substring=SETUP_OPENWIKI_TASK_DEDUP_KEY,
        preview_relpath=OPENWIKI_PAGE_MANIFEST_RELPATH,
        target_is_dir=True,
    )


def create_openwiki_setup_task(board_slug: str, actor: str = "user") -> dict[str, Any]:
    """Create or return an existing setup task to generate openwiki/ documentation."""
    return create_setup_task(
        board_slug,
        status_checker=check_board_openwiki_status,
        title=SETUP_OPENWIKI_TASK_TITLE,
        prompt_builder=build_openwiki_setup_task_prompt,
        files=[
            OPENWIKI_RELATIVE_DIR,
            OPENWIKI_PAGE_MANIFEST_RELPATH,
            "AGENTS.md",
        ],
        dedup_key=SETUP_OPENWIKI_TASK_DEDUP_KEY,
        progress_label="OpenWiki",
        created_label="OpenWiki",
        actor=actor,
    )
