"""Zero Factory OpenWiki Service — Status detection, prompt generation, and setup task management."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

_PLUGIN_ROOT = str(Path(__file__).resolve().parent.parent)
if _PLUGIN_ROOT not in sys.path:
    sys.path.insert(0, _PLUGIN_ROOT)
_DASHBOARD_ROOT = str(Path(__file__).resolve().parent)
if _DASHBOARD_ROOT not in sys.path:
    sys.path.insert(0, _DASHBOARD_ROOT)

try:
    from .setup_common import (
        check_board_setup_status,
        create_setup_task,
        get_repo_resolver,  # noqa: F401  (re-exported for API compatibility)
    )
except (ImportError, ValueError):
    from setup_common import (  # type: ignore
        check_board_setup_status,
        create_setup_task,
        get_repo_resolver,  # noqa: F401  (re-exported for API compatibility)
    )

OPENWIKI_RELATIVE_DIR = "openwiki"
SETUP_OPENWIKI_TASK_TITLE = (
    "chore(repo): setup OpenWiki machine-readable agent documentation"
)
SETUP_OPENWIKI_TASK_DEDUP_KEY = "setup:openwiki"
SETUP_OPENWIKI_TASK_TITLE_PREFIX = "chore(repo): setup OpenWiki"


def build_openwiki_setup_task_prompt(
    board_slug: str, repo_path: Path | None = None
) -> str:
    """Generate structured instructions for zf-builder to generate OpenWiki agent docs via the openwiki CLI."""
    path_hint = f" (`{repo_path}`)" if repo_path else ""
    return f"""Set up OpenWiki machine-readable agent documentation for this repository{path_hint} on board `{board_slug}`.

## Target
Directory: `{OPENWIKI_RELATIVE_DIR}/` (generated by the `openwiki` CLI)
Pointers: `AGENTS.md` / `CLAUDE.md` (maintained by the `openwiki` CLI)

## Goal
Generate a high-signal, machine-readable architectural knowledge base in `{OPENWIKI_RELATIVE_DIR}/` (Docs for Agents pattern) using the **official `openwiki` CLI**, so agents consume the wiki instead of re-reading source. This optimizes context windows, slashes exploratory token consumption by 30–40%, and prevents multi-agent hallucination across Zero Factory workers (`zf-builder`, `zf-reviewer`, `zf-orchestrator`).

## Instructions
1. **Ensure the `openwiki` CLI is installed**:
   - Check: `openwiki --version` (requires Node.js >= 22.22.0).
   - If not installed, install it globally via npm:
     ```bash
     npm install -g openwiki
     ```
   - If a global install is impossible in this environment, run the same CLI on-demand: `npx -y openwiki --version`.

2. **Generate the wiki with the `openwiki` CLI — never manually**:
   - **CRITICAL: the wiki MUST be generated by the `openwiki` CLI. Do NOT hand-write, hand-structure, or manually create `{OPENWIKI_RELATIVE_DIR}/`, `AGENTS.md`, or `CLAUDE.md`.** If the CLI cannot complete a run in this environment, BLOCK the task (`hermes zerofactory block <task_id> --reason "<CLI error>"`) with the captured error output instead of falling back to manual wiki authoring.
   - Run from the repository root:
     ```bash
     openwiki --init
     ```
     Answer the onboarding prompts (provider, credentials, model) so the run completes; the CLI writes the generated wiki to `{OPENWIKI_RELATIVE_DIR}/` (including `{OPENWIKI_RELATIVE_DIR}/index.md` and `quickstart.md`).
   - Verify the CLI actually produced `{OPENWIKI_RELATIVE_DIR}/index.md` on disk before proceeding.

3. **Confirm agent pointers (CLI-managed)**:
   - The `openwiki` CLI maintains the `AGENTS.md` and `CLAUDE.md` managed block (`<!-- OPENWIKI:START --> ... <!-- OPENWIKI:END -->`) at the repository root itself — do NOT edit that block by hand.
   - If the CLI left `AGENTS.md` without any reference to `{OPENWIKI_RELATIVE_DIR}/`, add an explicit reference section OUTSIDE the managed block:
     ```markdown
     ## Repository Architecture & Agent Wiki
     For architectural overviews, subsystem maps, and module contracts, consult the machine-readable wiki in `{OPENWIKI_RELATIVE_DIR}/index.md` before reading individual source files.
     ```

4. **Verify Precommit Checks**:
   - Run `./.zerofactory/precommit.sh` (or `git status`) in the repository to verify that format, build, and test checks execute cleanly.
   - Ensure the generated markdown is clean, readable, and well-linked.

5. **Complete Task**:
   - Mark task done via `hermes zerofactory move <task_id> done`.
   - (NOTE: Do NOT run git add/commit/push manually. The dispatcher automatically verifies precommit and stages/commits/opens PR upon task completion).
"""


def check_board_openwiki_status(board_slug: str) -> dict[str, Any]:
    """Check if openwiki/ exists for a board and check active setup task status."""
    return check_board_setup_status(
        board_slug,
        has_key="has_openwiki",
        path_key="openwiki_path",
        preview_key="wiki_index_preview",
        target_relpath=OPENWIKI_RELATIVE_DIR,
        title_prefix=SETUP_OPENWIKI_TASK_TITLE_PREFIX,
        dedup_substring=SETUP_OPENWIKI_TASK_DEDUP_KEY,
        preview_relpath=f"{OPENWIKI_RELATIVE_DIR}/index.md",
        target_is_dir=True,
    )


def create_openwiki_setup_task(board_slug: str, actor: str = "user") -> dict[str, Any]:
    """Create or return an existing setup task to generate openwiki/ documentation."""
    return create_setup_task(
        board_slug,
        status_checker=check_board_openwiki_status,
        title=SETUP_OPENWIKI_TASK_TITLE,
        prompt_builder=build_openwiki_setup_task_prompt,
        files=[
            OPENWIKI_RELATIVE_DIR,
            f"{OPENWIKI_RELATIVE_DIR}/index.md",
            "AGENTS.md",
        ],
        dedup_key=SETUP_OPENWIKI_TASK_DEDUP_KEY,
        progress_label="OpenWiki",
        created_label="OpenWiki",
        actor=actor,
    )
